---
- name: Create a VM Snapshot
  hosts: local
  connection: local
  gather_facts: no
  collections:
    - requirements
  tasks:
    - name: Creating snapshot
      community.vmware.vmware_guest_snapshot:
        hostname: 192.168.50.10
        username: administrator@vsphere.local
        password: P@ssw0rd
        datacenter: "Solution Center"
        folder: "/Solution Center/RHEL"
        name: "RHEL8 VM1"
        state: present
        snapshot_name: "newsnapshot"
        delegate_to: localhost
