---
- name: This update a windows server
  hosts: winserver1
  tasks:
  - name: Copy a single folder
    ansible.windows.win_copy:
      src: C:\Users\Administrator\Desktop\Sample
      dest: C:\Users\Administrator\Desktop\Sample_BAK
