---
- name: This update a windows server
  hosts: winserver1
  tasks:
  - name: Update sec
    yum:
      name: '*'
      state: latest
      
#  - name: Install all updates and reboot as many times as needed
#  ansible.windows.win_updates:
#    category_names: '*'
#    reboot: yes

  - name: Install all security, critical, and rollup updates without a scheduled task
    ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
